replicaCount: 1
image:
  name: consensys/maru:1b02f6f
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    - name: api
      port: 5060
    - name: p2p
      port: 9000
      protocol: TCP
    - name: discovery
      port: 9000
      protocol: UDP
    - name: metrics
      port: 9545
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""
configFiles:
  privateKey: |
  configsDefaultsToml: |
    allow-empty-blocks = true

    [persistence]
    data-path="/opt/consensys/maru/data/db"
    private-key-path="/opt/consensys/maru/configs/private-key.txt"

    [p2p]
    ip-address = "0.0.0.0"

    [p2p.discovery]
    refresh-interval = "5 seconds"

    [syncing]
    peer-chain-height-polling-interval = "5 seconds"
    el-sync-status-refresh-interval = "5 seconds"
    use-unconditional-random-download-peer = false
    sync-target-selection = "Highest"

    [observability]
    port = 9545

    [api]
    port = 5060
  configsToml: |
  genesisJson: |
    {
      "chainId": 1337,
      "config": {
        "1683325137": {
          "type": "qbft",
          "validatorSet": ["0x1b9abeec3215d8ade8a33607f2cf0f4f60e5f0d0"],
          "blockTimeSeconds": 1,
          "feeRecipient": "0x0000000000000000000000000000000000000000",
          "elFork": "Prague"
        }
      }
    }
  log4j: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="INFO" monitorInterval="2">
    <Appenders>
      <Console name="Console" target="SYSTEM_OUT">
        <PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss.SSS}{UTC} | %-5level | %c{1} | %msg %throwable%n" />
      </Console>
    </Appenders>
    <Loggers>
     <Logger name="org.hyperledger.besu" level="INFO"/>
      <Logger name="tech.pegasys.teku" level="INFO"/>
      <Logger name="maru" level="INFO"/>
      <Logger name="maru.syncing" level="DEBUG"/>
      <Logger name="clients" level="DEBUG"/>
      <Root level="INFO">
        <AppenderRef ref="Console"/>
      </Root>
    </Loggers>
    </Configuration>
