[persistence]
data-path="/tmp/maru-db"
private-key-path="/tmp/maru-db/private-key"

[qbft-options]
fee-recipient = "0x0000000000000000000000000000000000000000"

[p2p-config]
port = 3322
ip-address = "127.0.0.1"
discovery-enabled = false
discovery-port = 0
static-peers = []
reconnect-delay = 500
bootnodes = ["enr:-Iu4QHk0YN5IRRnufqsWkbO6Tn0iGTx4H_hnyiIEdXDuhIe0KKrxmaECisyvO40mEmmqKLhz_tdIhx2yFBK8XFKhvxABgmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQOgBvD-dv0cX5szOeEsiAMtwxnP1q5CA5toYDrgUyOhV4N0Y3CCJBKDdWRwgiQT"]

[payload-validator]
engine-api-endpoint = { endpoint = "http://sequencer:8550" }
eth-api-endpoint = { endpoint = "http://sequencer:8545" }

[follower-engine-apis]
"follower-besu" = { endpoint = "http://follower-besu:8550" }
"follower-erigon" = { endpoint = "http://follower-erigon:8551", jwt-secret-path = "../docker/jwt" }
"follower-nethermind" = { endpoint = "http://follower-nethermind:8550", jwt-secret-path = "../docker/jwt" }
"follower-geth" = { endpoint = "http://follower-geth:8551", jwt-secret-path = "../docker/jwt" }

[observability-options]
port = 9090
jvm-metrics-enabled = true
prometheus-metrics-enabled = true

[api-config]
port = 8080
