allow-empty-blocks = true

[persistence]
data-path="/tmp/maru-db"
private-key-path="/tmp/maru-db/private-key"

[qbft]
fee-recipient = "0x0000000000000000000000000000000000000000"

[p2p]
port = 3322
ip-address = "0.0.0.0"
static-peers = []
reconnect-delay = "500 ms"

[p2p.discovery]
port = 3324
bootnodes = ["enr:-Iu4QHk0YN5IRRnufqsWkbO6Tn0iGTx4H_hnyiIEdXDuhIe0KKrxmaECisyvO40mEmmqKLhz_tdIhx2yFBK8XFKhvxABgmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQOgBvD-dv0cX5szOeEsiAMtwxnP1q5CA5toYDrgUyOhV4N0Y3CCJBKDdWRwgiQT"]
refresh-interval = "2 minutes"

[payload-validator]
engine-api-endpoint = { endpoint = "http://sequencer:8550" }
eth-api-endpoint = { endpoint = "http://sequencer:8545" }

[follower-engine-apis]
"follower-besu" = { endpoint = "http://follower-besu:8550" }
"follower-erigon" = { endpoint = "http://follower-erigon:8551", jwt-secret-path = "../docker/jwt" }
"follower-nethermind" = { endpoint = "http://follower-nethermind:8550", jwt-secret-path = "../docker/jwt" }
"follower-geth" = { endpoint = "http://follower-geth:8551", jwt-secret-path = "../docker/jwt" }

[observability]
port = 9090
jvm-metrics-enabled = true
prometheus-metrics-enabled = true

[api]
port = 8080

[syncing]
peer-chain-height-polling-interval = "5 seconds"
el-sync-status-refresh-interval = "5 seconds"
use-unconditional-random-download-peer = false
sync-target-selector = "Highest"

[syncing.sync-target-selector.most-frequent] # effective only when type is "MostFrequent"
peer-chain-height-granularity = 10
