[sot-endpoint]
endpoint = "http://sequencer:8545"

[dummy-consensus-options]
communication-time-margin=100m

[p2p-config]
port = 3322

[validator]
private-key = "0xdead"
jwt-secret-path = "/secret/path"
min-time-between-get-payload-attempts=800m
el-client-endpoint = "http://sequencer:8545"
