[plugins]
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.5" }
errorprone = { id = "net.ltgt.errorprone", version = "4.0.1" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version = "2.0.10" }
