replicaCount: 1
fullnameOverride: maru-follower-3
configFiles:
  privateKey: |
    0x0802122100cb876c984d90b683011e93321be79d6f384e6cc78b1b0f1f882b20d00fe89022
  configsToml: |
    [payload-validator]
    engine-api-endpoint = { endpoint = "http://besu-follower-3.besu-follower.default.svc.cluster.local:8550" }
    eth-api-endpoint = { endpoint = "http://besu-follower-3.besu-follower.default.svc.cluster.local:8545" }

    [follower-engine-apis]
    follower-besu = { endpoint = "http://besu-follower-4.besu-follower.default.svc.cluster.local:8550" }

  log4j: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="INFO" monitorInterval="2">
    <Appenders>
      <Console name="Console" target="SYSTEM_OUT">
        <PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss.SSSZZZ} | %t | %-5level | %c{1} | %msg %throwable%n" />
      </Console>
    </Appenders>
    <Loggers>
      <Logger name="org.hyperledger.besu" level="INFO"/>
      <Logger name="tech.pegasys.teku" level="INFO"/>
      <Logger name="maru.syncing" level="DEBUG"/>
      <Logger name="maru" level="INFO"/>
      <Logger name="clients" level="DEBUG"/>
      <Root level="INFO">
        <AppenderRef ref="Console"/>
      </Root>
    </Loggers>
    </Configuration>
