replicaCount: 1
fullnameOverride: maru-follower-2
configFiles:
  privateKey: |
    0x0802122007ff78e0ad0e7c04553bceeb52d0962980c7b1406320515c5baabfe9951fd424
  configsToml: |
    [payload-validator]
    engine-api-endpoint = { endpoint = "http://besu-follower-2.besu-follower.default.svc.cluster.local:8550" }
    eth-api-endpoint = { endpoint = "http://besu-follower-2.besu-follower.default.svc.cluster.local:8545" }

  log4j: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="INFO" monitorInterval="2">
    <Appenders>
      <Console name="Console" target="SYSTEM_OUT">
        <PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss.SSSZZZ} | %t | %-5level | %c{1} | %msg %throwable%n" />
      </Console>
    </Appenders>
    <Loggers>
      <Logger name="org.hyperledger.besu" level="INFO"/>
      <Logger name="tech.pegasys.teku" level="INFO"/>
      <Logger name="maru" level="INFO"/>
      <Logger name="maru.syncing" level="DEBUG"/>
      <Logger name="clients" level="DEBUG"/>
      <Root level="INFO">
        <AppenderRef ref="Console"/>
      </Root>
    </Loggers>
    </Configuration>
