datadir = "/home/erigon"
networkid = 1337
port = 30301
ethstats = ""
netrestrict = "11.11.11.0/24"

"miner.gaslimit" = "0x1C9C380"

"http.addr" = "0.0.0.0"
"http.port" = 8545
"http.corsdomain" = "*"
"http.api" = ["admin","engine","eth","net","web3","txpool","debug"]
"http.vhosts" ="*"

"authrpc.port" = 8551
"authrpc.vhosts" = "*"
"authrpc.addr" = "0.0.0.0"
"authrpc.jwtsecret" = "/jwt"
