apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "besu.fullname" . }}
  labels:
    app: {{ include "besu.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "besu.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "besu.name" . }}
    spec:
      containers:
        - name: {{ include "besu.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /opt/besu/bin/besu
            - --config-file=/opt/besu/configs/configs.toml
            - --genesis-file=/opt/besu/configs/genesis.json
            - --node-private-key-file="/opt/besu/configs/private-key.txt"
          volumeMounts:
            - name: data
              mountPath: /opt/besu/data
            - name: configs
              mountPath: /opt/besu/configs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "besu.fullname" . }}-data-pvc
        - name: configs
          configMap:
            name: {{ include "besu.fullname" . }}-configs
