apiVersion: v1
kind: Service
metadata:
  name: {{ include "besu.fullname" . }}
  labels:
    {{- include "besu.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  {{ if .Values.service.headless }}
  clusterIP: None
  {{ end }}
  selector:
    {{- include "besu.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.ethApiPort }}
      targetPort: {{ .Values.service.ethApiPort }}
      protocol: TCP
      name: eth-api
    - port: {{ .Values.service.engineApiPort }}
      targetPort: {{ .Values.service.engineApiPort }}
      protocol: TCP
      name: engine-api
    - port: {{ .Values.service.p2pPort }}
      targetPort: {{ .Values.service.p2pPort }}
      protocol: TCP
      name: p2p
    - port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}
      protocol: TCP
      name: metrics
