apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "maru.fullname" . }}-configs
  labels:
    {{- include "maru.labels" . | nindent 4 }}
data:
  genesis.json: |-
    {{- .Values.configFiles.genesisJson | nindent 4 }}
  configs.toml: |-
    {{- .Values.configFiles.configsToml | nindent 4 }}
  log4j.xml: |-
    {{- .Values.configFiles.log4j | nindent 4 }}
  private-key.txt: |-
    {{- .Values.configFiles.privateKey | nindent 4 }}
