apiVersion: v1
kind: Service
metadata:
  name: {{ include "maru.fullname" . }}
  labels:
    {{- include "maru.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  selector:
    {{- include "maru.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.p2pPort }}
      targetPort: {{ .Values.service.p2pPort }}
      protocol: TCP
      name: observability
    - port: {{ .Values.service.observabilityPort }}
      targetPort: {{ .Values.service.observabilityPort }}
      protocol: TCP
      name: p2p
    - port: {{ .Values.service.discoveryPort }}
      targetPort: {{ .Values.service.discoveryPort }}
      protocol: TCP
      name: discovery
