apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "maru.fullname" . }}
  labels:
    {{- include "maru.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "maru.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "maru.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "maru.labels" . | nindent 8 }}
    spec:
      containers:
        - name: maru
          image: "{{ .Values.image.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - java
            - -Dlog4j2.configurationFile=configs/log4j.xml
            - -jar
            - maru.jar
            - --maru-genesis-file
            - /opt/consensys/maru/configs/genesis.json
            - --config
            - /opt/consensys/maru/configs/configs.toml
          volumeMounts:
            - name: data
              mountPath: /opt/consensys/maru/data
            - name: configs
              mountPath: /opt/consensys/maru/configs
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: TCP
            {{- end }}
      volumes:
        - name: configs
          configMap:
            name: {{ include "maru.fullname" . }}-configs
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "{{ $.Values.persistence.accessMode }}" ]
        resources:
          requests:
            storage: {{ $.Values.persistence.size }}
          {{- if $.Values.persistence.storageClass }}
        storageClassName: {{ $.Values.persistence.storageClass }}
          {{- end }}
