name: main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  filter-commit-changes:
    runs-on: [gha-runner-scale-set-ubuntu-22.04-amd64-small]
    name: Filter commit changes
    outputs:
      consensus-client: ${{ steps.filter.outputs.consensus-client }}
      has-changes-requiring-build: ${{ steps.filter-out.outputs.has-changes-requiring-build }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter commit changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref }}
          list-files: "json"
          filters: |
            consensus-client:
              - 'buildSrc/**'
              - 'config/**'
              - 'consensus/**'
              - 'core/**'
              - 'crypto/**'
              - 'executionlayer/**'
              - 'jvm-libs/**'
              - 'p2p/**'
              - 'serialization/**'
              - 'storage/**'
              - 'build.gradle'

      - name: Filter out commit changes
        uses: dorny/paths-filter@v3
        id: filter-out
        with:
          base: ${{ github.ref }}
          list-files: "json"
          filters: |
            has-changes-requiring-build:
              - '!**/*.md'
              - '!docs/**'

  testing:
    needs: [ filter-commit-changes ]
    if: ${{ always() && !cancelled() && needs.filter-commit-changes.outputs.has-changes-requiring-build == 'true' }}
    uses: ./.github/workflows/testing.yml
    with:
#      commit-tag: ${{ needs.store-image-name-and-tags.outputs.commit_tag }}
      consensus-client-changed: ${{ needs.filter-commit-changes.outputs.consensus-client }}
    secrets: inherit

  run-e2e-tests:
    needs: [ filter-commit-changes ]
    if: ${{ always() && !cancelled() && needs.filter-commit-changes.outputs.has-changes-requiring-build == 'true' }}
    concurrency:
      group: run-e2e-tests-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    uses: ./.github/workflows/e2e-tests.yml
    with:
#      commit-tag: ${{ needs.store-image-name-and-tags.outputs.commit-tag }}
      e2e-tests-logs-dump: true
      has-changes-requiring-build: ${{ needs.filter-commit-changes.outputs.has-changes-requiring-build }}
    secrets: inherit

  compute-commit-hash:
    runs-on: [gha-runner-scale-set-ubuntu-22.04-amd64-small]
    outputs:
      commithash: ${{ steps.compute-commit-hash.outputs.commithash }}
    steps:
      - name: Compute commit hash
        id: compute-commit-hash
        shell: bash
        run: |
          # For PR, GITHUB_SHA is NOT the last commit pushed onto the PR branch - https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "commithash=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})" >> $GITHUB_OUTPUT
          else
            echo "commithash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT
          fi

  build-and-publish:
    needs: [ compute-commit-hash, testing, run-e2e-tests ]
    if: ${{ always() && !cancelled() && needs.testing.result == 'success' && needs.run-e2e-tests.outputs.tests_outcome == 'success' }}
    uses: ./.github/workflows/maru-build-and-publish.yml
    with:
      commit_tag: needs.compute-commit-hash.outputs.commithash
      develop_tag: 'develop'
      image_name: 'consensys/maru'
      push_image: true
    secrets: inherit
