name: main

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: maru-main-workflow-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  filter-commit-changes:
    runs-on: [gha-runner-scale-set-ubuntu-22.04-amd64-small]
    name: Filter commit changes
    outputs:
      consensus-client: ${{ steps.filter.outputs.consensus-client }}
      has-changes-requiring-build: ${{ steps.filter-out.outputs.has-changes-requiring-build }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter commit changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          # Use proper base for comparison - target branch for PRs, previous commit for push
          base: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || 'HEAD~1' }}
          list-files: "json"
          filters: |
            consensus-client:
              - '**'

      - name: Filter out commit changes
        uses: dorny/paths-filter@v3
        id: filter-out
        with:
          # Use proper base for comparison - target branch for PRs, previous commit for push
          base: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || 'HEAD~1' }}
          list-files: "json"
          filters: |
            has-changes-requiring-build:
              - '!**/*.md'
              - '!docs/**'
              - '!chaos-testing/**'

  testing:
    needs: [ filter-commit-changes ]
    if: ${{ always() && !cancelled() && needs.filter-commit-changes.outputs.has-changes-requiring-build == 'true' }}
    uses: ./.github/workflows/testing.yml
    with:
      consensus-client-changed: ${{ needs.filter-commit-changes.outputs.consensus-client }}
    secrets: inherit

  run-e2e-tests:
    needs: [ filter-commit-changes ]
    if: ${{ always() && !cancelled() && needs.filter-commit-changes.outputs.has-changes-requiring-build == 'true' }}
    uses: ./.github/workflows/e2e-tests.yml
    with:
      e2e-tests-logs-dump: true
      has-changes-requiring-build: ${{ needs.filter-commit-changes.outputs.has-changes-requiring-build }}
    secrets: inherit

  chaos-testing:
    needs: [ filter-commit-changes ]
    if: ${{ always() && !cancelled() && needs.filter-commit-changes.outputs.has-changes-requiring-build == 'true' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/chaos-testing.yml
    with:
      consensus-client-changed: ${{ needs.filter-commit-changes.outputs.consensus-client }}
    secrets: inherit

  build-for-testing:
    if: ${{ always() && !cancelled() }}
    uses: ./.github/workflows/maru-build-and-publish.yml
    with:
      develop_tag: 'develop'
      image_name: 'consensys/maru'
      push_image: false
    secrets: inherit

  maru-image-smoke-test:
    needs: [ build-for-testing ]
    uses: ./.github/workflows/smoke-tests.yml
    with:
      commit-tag: ${{ needs.build-for-testing.outputs.commit_tag }}
    secrets: inherit

  build-and-publish:
    needs: [ maru-image-smoke-test ]
    if: ${{ always() && !cancelled() && needs.maru-image-smoke-test.result == 'success' && (github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main') }}
    uses: ./.github/workflows/maru-build-and-publish.yml
    with:
      develop_tag: 'develop'
      image_name: 'consensys/maru'
      push_image: true
    secrets: inherit
