name: Testing CI

on:
  workflow_call:
    inputs:
      #      commit-tag:
      #        required: true
      #        type: string
      consensus-client-changed:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

concurrency:
  group: consensus-client-testing-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  run-tests:
    if: ${{ inputs.consensus-client-changed == 'true' }}
    env:
      COMMIT_TAG: ${{ inputs.commit_tag }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    runs-on: [ gha-runner-scale-set-ubuntu-22.04-amd64-med ]
    name: Consensus client tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326 # 4.4.0
      - name: Build consensus and Unit tests
        run: |
          make build
      #      - name: Login to Docker Hub
      #        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
      #        uses: docker/login-action@v3
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #      - name: Run integration tests
      #        timeout-minutes: 15
      #        run: |
      #          ./gradlew app:integrationTestAllNeeded
      - name: Run Jacoco
        run: |
          ./gradlew jacocoAggregatedReport
      - name: Upload Jacoco test coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacocoRootReport-${{ env.COMMIT_TAG }}.xml
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/build/reports/jacoco/jacocoAggregatedReport/jacocoAggregatedReport.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ${{ github.workspace }}/build/reports/jacoco/jacocoAggregatedReport/jacocoAggregatedReport.xml
          flags: kotlin
          os: linux
          name: codecov
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
